import type {Metadata} from 'next';
import './globals.css';
import Header from './components/header/Header';
import Modal from './components/modal/Modal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased text-sm`}>
        <Header />
        <Modal />
        {children}
      </body>
    </html>
  );
}
